 export const ACTIVITY_TYPES = [
    'all',
  'feature',
  'improvement',
  'enhancement',
  'bug-fix',
  'security',
  'performance',
  'refactor',
  'ui',
  'accessibility',
  'localization',
  'documentation',
  'dependency',
  'breaking-change',
  'deprecation',
  'removal',
  'maintenance',
  'other',
] as const;